"""
U-Net 기반 프리라벨 생성
========================
학습된 U-Net으로 이미지에 대한 세그멘테이션을 수행하고,
결과를 LabelMe JSON 포맷으로 저장.

- 이미 JSON이 있는 이미지는 스킵 (수동 라벨 보존)
- 사용자는 LabelMe에서 열어서 꼭짓점만 미세 조정하면 됨

사용법:
    python scripts/generate_prelabels.py                    # images_main/ 전체
    python scripts/generate_prelabels.py images_main 50     # 처음 50장만
    python scripts/generate_prelabels.py images_main --overwrite  # 기존 JSON도 덮어쓰기
    python scripts/generate_prelabels.py images_TNMX --recursive  # TNMX 하위폴더 재귀 처리
"""

import os
import sys
import json
import time
import argparse
import numpy as np
import cv2 as cv
from pathlib import Path

from datetime import datetime

import torch
import albumentations as A
from albumentations.pytorch import ToTensorV2
import segmentation_models_pytorch as smp

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODEL_PATH = PROJECT_ROOT / "dl" / "models" / "best_model.pth"
IMG_SIZE = 128
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# VT-S730 AOI 해상도: ~15 µm/pixel
PIXEL_SIZE_UM = 15.0
PIXEL_AREA_MM2 = (PIXEL_SIZE_UM / 1000.0) ** 2


def apply_clahe(img_rgb, clip_limit=3.0, grid_size=(8, 8)):
    """LAB 색공간 L채널에 CLAHE 적용. 학습·추론 동일하게 사용."""
    lab = cv.cvtColor(img_rgb, cv.COLOR_RGB2LAB)
    clahe = cv.createCLAHE(clipLimit=clip_limit, tileGridSize=grid_size)
    lab[:, :, 0] = clahe.apply(lab[:, :, 0])
    return cv.cvtColor(lab, cv.COLOR_LAB2RGB)


def load_model():
    model = smp.Unet(
        encoder_name="resnet18",
        encoder_weights=None,
        in_channels=3,
        classes=1,
    ).to(DEVICE)

    checkpoint = torch.load(MODEL_PATH, map_location=DEVICE, weights_only=True)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()
    print(f"모델 로드: epoch {checkpoint['epoch']}, Val IoU={checkpoint['val_iou']:.4f}")
    return model


def get_transform():
    return A.Compose([
        A.Resize(IMG_SIZE, IMG_SIZE),
        A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ToTensorV2(),
    ])


@torch.no_grad()
def predict_mask(model, img_bgr, transform):
    """이미지에서 바이너리 마스크 예측."""
    h, w = img_bgr.shape[:2]
    img_rgb = cv.cvtColor(img_bgr, cv.COLOR_BGR2RGB)

    # CLAHE 전처리 (학습과 동일하게 적용)
    img_rgb = apply_clahe(img_rgb)

    augmented = transform(image=img_rgb, mask=np.zeros((h, w), dtype=np.float32))
    img_tensor = augmented["image"].unsqueeze(0).to(DEVICE)

    pred = torch.sigmoid(model(img_tensor)).squeeze().cpu().numpy()
    pred_mask = (pred > 0.5).astype(np.uint8) * 255

    return cv.resize(pred_mask, (w, h), interpolation=cv.INTER_NEAREST)


def mask_to_labelme_json(mask, img_path, epsilon_ratio=0.02):
    """바이너리 마스크 → LabelMe JSON 포맷 변환.

    Args:
        mask: 바이너리 마스크 (0/255)
        img_path: 이미지 파일 경로
        epsilon_ratio: 폴리곤 단순화 비율 (둘레의 %). 작을수록 정교.
    """
    h, w = mask.shape[:2]

    # 컨투어 추출
    contours, _ = cv.findContours(mask, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)

    shapes = []
    for contour in contours:
        # 너무 작은 컨투어 제거
        area = cv.contourArea(contour)
        if area < 20:
            continue

        # 폴리곤 단순화 (꼭짓점 줄이기 → LabelMe에서 편집 용이)
        epsilon = epsilon_ratio * cv.arcLength(contour, True)
        approx = cv.approxPolyDP(contour, epsilon, True)

        # 최소 3개 꼭짓점 필요
        if len(approx) < 3:
            continue

        # OpenCV 컨투어 → LabelMe 포인트 변환
        points = approx.squeeze().tolist()

        shapes.append({
            "label": "solder_paste",
            "points": points,
            "group_id": None,
            "description": "auto-generated by U-Net",
            "shape_type": "polygon",
            "flags": {},
            "mask": None,
        })

    labelme_data = {
        "version": "5.11.3",
        "flags": {},
        "shapes": shapes,
        "imagePath": Path(img_path).name,
        "imageData": None,
        "imageHeight": h,
        "imageWidth": w,
    }

    return labelme_data


def _collect_recursive(source_dir):
    """TNMX config 기반으로 include 폴더의 이미지 수집."""
    config_path = source_dir / ".tnmx_folder_config.json"
    if config_path.exists():
        with open(config_path, 'r', encoding='utf-8') as f:
            config = json.load(f)
        included = [e["folder"] for e in config["folders"]
                    if e["status"] == "include"]
        print(f"Config 로드: {len(included)}개 폴더 (include)")
    else:
        # config 없으면 모든 하위폴더 포함
        included = [d.name for d in sorted(source_dir.iterdir()) if d.is_dir()]
        print(f"Config 없음: 모든 하위폴더 ({len(included)}개) 포함")

    img_paths = []
    for folder_name in included:
        folder = source_dir / folder_name
        if folder.exists():
            imgs = sorted(folder.glob("*.png"))
            img_paths.extend(imgs)

    return img_paths


def _save_meta(source_dir, success, empty, existing):
    """단일 디렉토리용 메타데이터 저장."""
    meta_path = source_dir / ".prelabel_meta.json"
    meta = {
        "batch_end_time": time.time(),
        "batch_end_str": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "generated_count": success,
        "skipped_empty": empty,
        "skipped_existing": existing,
    }
    if meta_path.exists():
        with open(meta_path, 'r', encoding='utf-8') as f:
            old_meta = json.load(f)
        history = old_meta.get("history", [])
        history.append({"batch_end_time": old_meta["batch_end_time"],
                        "batch_end_str": old_meta["batch_end_str"],
                        "generated_count": old_meta["generated_count"]})
        meta["history"] = history
    with open(meta_path, 'w', encoding='utf-8') as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)
    print(f"\n배치 타임스탬프 저장: {meta_path}")


def _save_recursive_meta(source_dir, processed_paths, success, empty, existing):
    """재귀 모드: 각 하위폴더별 메타데이터 저장."""
    # 하위폴더별 그룹화
    from collections import defaultdict
    folder_counts = defaultdict(int)
    for p in processed_paths:
        folder_counts[p.parent] += 1

    saved = 0
    for folder, count in folder_counts.items():
        meta_path = folder / ".prelabel_meta.json"
        meta = {
            "batch_end_time": time.time(),
            "batch_end_str": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "generated_count": count,
            "recursive_batch": True,
        }
        if meta_path.exists():
            with open(meta_path, 'r', encoding='utf-8') as f:
                old_meta = json.load(f)
            history = old_meta.get("history", [])
            history.append({"batch_end_time": old_meta["batch_end_time"],
                            "batch_end_str": old_meta["batch_end_str"],
                            "generated_count": old_meta.get("generated_count", 0)})
            meta["history"] = history
        with open(meta_path, 'w', encoding='utf-8') as f:
            json.dump(meta, f, indent=2, ensure_ascii=False)
        saved += 1

    print(f"\n배치 타임스탬프 저장: {saved}개 폴더")


def main():
    parser = argparse.ArgumentParser(description="U-Net 프리라벨 생성")
    parser.add_argument("source_dir", nargs="?", default="images_main",
                        help="소스 이미지 디렉토리 (기본: images_main)")
    parser.add_argument("limit", nargs="?", type=int, default=0,
                        help="처리할 최대 이미지 수 (0=전체)")
    parser.add_argument("--overwrite", action="store_true",
                        help="기존 JSON 파일도 덮어쓰기")
    parser.add_argument("--recursive", action="store_true",
                        help="하위폴더 재귀 처리 (TNMX config 기반)")
    args = parser.parse_args()

    source_dir = Path(args.source_dir)
    if not source_dir.is_absolute():
        source_dir = PROJECT_ROOT / source_dir

    print("=" * 60)
    print("U-Net 프리라벨 생성")
    print("=" * 60)

    model = load_model()
    transform = get_transform()

    # 이미지 목록 수집
    if args.recursive:
        img_paths = _collect_recursive(source_dir)
    else:
        img_paths = sorted([p for p in source_dir.glob("*.png")
                            if p.suffix.lower() in ('.png', '.jpg', '.bmp')])

    if args.limit > 0:
        img_paths = img_paths[:args.limit]

    # 기존 JSON 확인
    existing = 0
    to_process = []
    for img_path in img_paths:
        json_path = img_path.with_suffix(".json")
        if json_path.exists() and not args.overwrite:
            existing += 1
        else:
            to_process.append(img_path)

    print(f"\n총 이미지: {len(img_paths)}개")
    print(f"기존 JSON (스킵): {existing}개")
    print(f"프리라벨 생성 대상: {len(to_process)}개")
    if args.overwrite:
        print("  (--overwrite 모드: 기존 JSON도 덮어씀)")
    if args.recursive:
        print("  (--recursive 모드: 하위폴더 재귀 처리)")

    if len(to_process) == 0:
        print("\n처리할 이미지가 없습니다.")
        return

    # 프리라벨 생성
    success = 0
    empty = 0
    current_subfolder = None
    for i, img_path in enumerate(to_process):
        # 하위폴더 변경 시 표시
        if args.recursive and img_path.parent != source_dir:
            subfolder = img_path.parent.name
            if subfolder != current_subfolder:
                current_subfolder = subfolder
                remaining_in_folder = sum(1 for p in to_process[i:]
                                          if p.parent.name == subfolder)
                print(f"\n  📁 {subfolder} ({remaining_in_folder}장)")

        img = cv.imread(str(img_path))
        if img is None:
            continue

        mask = predict_mask(model, img, transform)
        labelme_data = mask_to_labelme_json(mask, img_path)

        if len(labelme_data["shapes"]) == 0:
            empty += 1
            continue

        json_path = img_path.with_suffix(".json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(labelme_data, f, indent=2, ensure_ascii=False)

        success += 1

        if (i + 1) % 500 == 0 or i < 3:
            n_pts = sum(len(s["points"]) for s in labelme_data["shapes"])
            n_shapes = len(labelme_data["shapes"])
            solder_px = np.count_nonzero(mask)
            area_mm2 = solder_px * PIXEL_AREA_MM2
            print(f"  [{i+1}/{len(to_process)}] {img_path.name} → "
                  f"{n_shapes}개 폴리곤, {n_pts}개 꼭짓점, {area_mm2:.4f}mm²")

    # 배치 생성 완료 타임스탬프 저장 (재귀 모드에서는 각 하위폴더에 저장)
    if args.recursive:
        _save_recursive_meta(source_dir, to_process, success, empty, existing)
    else:
        _save_meta(source_dir, success, empty, existing)

    print(f"\n{'=' * 60}")
    print(f"완료: {success}개 JSON 생성, {empty}개 빈 예측 스킵")
    print(f"{'=' * 60}")
    if not args.recursive:
        print(f"\n다음 단계:")
        print(f"  labelme {source_dir} --autosave")
        print(f"  → 자동 생성된 폴리곤 확인/수정 후 다음 이미지로 넘어가기")
    else:
        print(f"\n다음 단계:")
        print(f"  각 하위폴더에서 LabelMe로 라벨 검수:")
        print(f"  labelme {source_dir}/[폴더명] --autosave")


if __name__ == "__main__":
    main()
